[package]
name = "splinosaurus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32"
num-traits = "0.2.17"

[dev-dependencies]
pixel-canvas = "0.2"